### ISSUE TITLE
Add tool to scale entire layout

### ISSUE THREAD

**Issue by dericke** [ijprest/keyboard-layout-editor#189]
I'm trying to make a cheat sheet for an application I use, complete with the alt, shift, and ctrl variants on each key. Even with the smallest font, the keys get too cluttered to read. I'd love a tool to scale everything but the text larger, so that I can fit everything in, and without having to resize the keys one-at-a-time.

**Comment by ijprest** [comment]
Possible workaround:  Use the custom styles tab and enter some CSS to set some really small fonts.  Something like this:
```css
/* set the size for all keycaps */
.keylabel { font-size: 8px !important; }

/* set different sizes for each legend/text value */
.keylabel.textsize1 { font-size: 4px !important; }
.keylabel.textsize2 { font-size: 6px !important; }
/* etc */
```

Then you use your browser's zoom functions to make everything bigger/readable.

(Note: I reserve the right to change the internals, so so I can't guarantee your custom CSS will work forever... but I don't expect it'll change anytime soon.)
