### ISSUE TITLE
custom key border color

### ISSUE THREAD

**Issue by freMea** [ijprest/keyboard-layout-editor#239]
Hi,

I'd like to customize key border color. Since there is no option for that in **properties** tab (I wish a such option exists), I tried **custom styles**.

The only rule that works is :
```css
.keyborder {
    border-color: rgba(255,255,255,.3) !important;
}
```
Without `!important`, it's not applied but if used, then, the selected and hover border color doesn't work anymore. So, it is not a viable solution in edition mode but can still be applied when the work is finished.

The **custom styles** doesn't support nested element so there is no workaround like applying a custom border color for selected key: `#keyboard .selected > .keycap > .keyborder` (inspired by the generated rule by the app) below the above rule with `!important` won't change anything.

## PLUS…

I wish there were another key profile named **PLAIN** that get rid of any 3D effect. Currently, the way to achieve that is applying this CSS:

```css
.keytop,
.keylabels {
    border-color: transparent !important;
}
.keytop {
    background-color: transparent !important;
}
```

**Comment by ijprest** [comment]
I've deployed a tweak to the templates & CSS that will allow you modify the border color without having to use `!important` (which will in-turn allow the hover & selected borders to still work).  E.g., just use this:
```css
.keyborder {
    border-color: rgba(255,255,255,.3);
}
```

For your second request... it would be pretty easy to do, but what's the use-case?  (I'm just wondering how/why it would be used, to make sure it's done in the best way.)
