### ISSUE TITLE
Is it possible to use fonts on my computer?

### ISSUE THREAD

**Issue by alessio-cpt** [ijprest/keyboard-layout-editor#241]
I'm trying to edit the CSS in the tab custom styles in order to use a particular font I have installed on my machine but it does not seem to work. Is it possible? How can I do it?

**Comment by ijprest** [comment]
If the font is installed on your system and available to the browser, it should be as easy as this:
```css
.keylabel0, .keylabel1, .keylabel2, 
.keylabel3, .keylabel4, .keylabel5, 
.keylabel6, .keylabel7, .keylabel8, 
.keylabel9, .keylabel10, .keylabel11 { 
   font-family: 'Bernard MT Condensed';
}
```

(Note, specifying all the `.keylabelXX` classes like this is currently preferred to using `*` due to #143.)
