### ISSUE TITLE
Numpad Keys bad display

### ISSUE THREAD

**Issue by ArmynC** [ijprest/keyboard-layout-editor#253]
The numpads PLUS and ENTER keys are broken when I changed the height... It should be orange over all the key...

![capture](https://user-images.githubusercontent.com/16375271/51276187-b152bd80-19dc-11e9-9bd5-0ba3e8377ef4.PNG)

```
.keytop { 
    height: 38px !important; 
}

.keylabel9, .keylabel10, .keylabel11 { 
    margin-top: -3px;
}
```

**Comment by ijprest** [comment]
That's what I meant by my "this won't work well if you have any keys > 1u tall" comment in #252.  :)

You can do something like this, though.  Adjust & repeat as necessary for other key heights.
```css
.keytop[style*="height: 42px;"] { 
    height: 38px !important; 
}
.keytop[style*="height: 96px;"] { 
    height: 92px !important; 
}
```

**Comment by ArmynC** [comment]
Oh, I thought first time that was abotu that .keyborder.. anyway it works :)

One more question.. with all of these modifications the key "Homing" (that key bump) isn't visible anymore.. how I can restore or mimic it?

**Comment by ijprest** [comment]
The homing bump (on DCS/OEM/normal profile keycaps) is done with a background image on the `.keylabels` div, which we'd need to move up (`background-position`).

There's unfortunately no way (currently) to target the homing keys individually/directly.  However, since this is probably the *only* `background-image` on any `.keylabels`, you can probably get away with this:

```css
.keylabels {
  background-position: center 80%; /*default is 90%*/
}
```
