### ISSUE TITLE
Working Dockerfile to run it locally?

### ISSUE THREAD

**Issue by spamwax** [ijprest/keyboard-layout-editor#358]
I tried to set up a Dockerfile to install and run this locally since I cannot save my layouts to github.
However after following the [instructions](https://github.com/ijprest/keyboard-layout-editor#getting-started-for-developers) at the end of README.md, and when I invoke `webdriver-manager update`, I get errors.

I was wondering if anyone has a working Dockerfile

```ini
[23:18:51] E/downloader - options.uri is a required argument
[23:18:51] I/update - chromedriver: file exists /usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_114.0.5735.90.zip
[23:18:51] I/update - chromedriver: unzipping chromedriver_114.0.5735.90.zip
/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/cmds/update.js:232
            throw new Error(`Invalid filename: ${path.resolve(outputDir, fileName)}`);
                  ^

Error: Invalid filename: /usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_114.0.5735.90.zip
    at unzip (/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/cmds/update.js:232:19)
    at /usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/cmds/update.js:205:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 1)
```

**Comment by dcunited001** [comment]
It may be simpler to just launch multiple containers with docker compose.

The Dockerfile for the app should be fairly simple. It just needs `bower` dependencies, i think. 

The Dockerfile for the tests should also be simple, but just needs "selenium-standalone" dependencies.

**Comment by guest20** [comment]
This is the dockerfile I use as the base for my build
```dockerfile
FROM node:21

RUN DEBIAN_FRONTEND=noninteractive apt-get update --allow-releaseinfo-change                      && \
    DEBIAN_FRONTEND=noninteractive apt-get install --force-yes -y fontforge nodejs npm   uglifyjs && \
   npm install  --trace-deprecation  -yqg bower         && \
   npm install  --trace-deprecation  -yqg grunt-cli     && \
   npm install  --trace-deprecation  -yqg protractor    && \
   npm install  --trace-deprecation  -yqg jasmine       && \
   npm install  --trace-deprecation  -yqg uglifyjs      && \
  # npm WARN deprecated uglifyjs@2.4.11: uglifyjs is deprecated - use uglify-js instead.
  # npm install -yqg uglify-js      && \ 
   npm install  --trace-deprecation  -yqg stylus        && \
   npm install  --trace-deprecation  -yqg jison         && \
   npm install  --trace-deprecation  -yqg git-utils     && \
   groupadd -r keyboard && useradd --no-log-init -r -g keyboard keyboard

```

You can likely shove the `script` part below into `RUN` statements after the `dockerfile` content above, but I prefer to to build/push a base image with the dependencies installed, so I don't have to wait for those `npm install`s to happen every time every time I push a change to kle.

Here's my `.gitlab-ci.yml`:

```yaml

stages:
  - building
pages:  
  services:
    - docker:dind
  stage: building
  image: <the one you built above >
  script:
    - |
      mkdir -p                    /usr/local/lib/node_modules/git-utils/  ;
      chown -R :keyboard  /usr/local/lib/node_modules/git-utils/  ;
      chmod -R g+rwx       /usr/local/lib/node_modules/git-utils/  ;
    - make install fonts all 
    - mkdir public/
    - cp -r css/ js/ fonts/ samples/ bg/ kb.html oauth.html kb.js render.js serial.js extensions.js favicon.ico ./*.md  ./*.json public/

  artifacts:
    paths: 
     - public/

```

I then because gitlab pages serve javascript with a messed up content type, I download the artefacts in a `.zip` and unpack it into the `docroot` on my server.

My fork also has a bunch of janky patches to use my own home-rolled oauth gatekeeper for github, but I later discovered I don't need them.

I think it's this gatekeeper: https://github.com/prose/gatekeeper

I'm sure I'm skipping the tests by doing this, but it's clear I'm not going to be doing any PRs back to the upstream, and since forks are not allowed under the licence there's no point in cleaning it up. 

HTH HAND
