### ISSUE TITLE
make website printer friendly

### ISSUE THREAD

**Issue by sunaku** [ijprest/keyboard-layout-editor#60]
Hello,

It wasn't possible to print _only_ the keyboard layout from [the website](http://www.keyboard-layout-editor.com/) so I created [this user style](https://userstyles.org/styles/101750/keyboard-layout-editor-printer-friendly) to hide everything except the keyboard layout from the browser's **Print** function. :necktie:

![Print Preview](https://df6a.https.cdn.softlayer.net/80DF6A/static.userstyles.org/style_screenshot_thumbnails/101750_after.png?r=1400625057)

``` css
@media print {
  #wrap > .navbar,
  #wrap > .body > .btn-group,
  #keyboard ~ *,
  #keyboard + *,
  #footer,
  #helpDialog {
    display: none;
  }
  #keyboard {
    border: none;
    background-color: inherit !important;
  }
}
```

Please consider incorporating this CSS into the codebase.  Thanks!
